export const ErrorCode = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INTERNAL_AUTH_FAILED: 'INTERNAL_AUTH_FAILED',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_PHOTO: 'INVALID_PHOTO',
  INVALID_PHOTO_TYPE: 'INVALID_PHOTO_TYPE',
  INVENTORY_DATABASE_UNAVAILABLE: 'INVENTORY_DATABASE_UNAVAILABLE',
  INVENTORY_RECORD_CONFLICT: 'INVENTORY_RECORD_CONFLICT',
  INVENTORY_RECORD_NOT_FOUND: 'INVENTORY_RECORD_NOT_FOUND',
  INVENTORY_INTERNAL_ERROR: 'INVENTORY_INTERNAL_ERROR',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_VERSION_CONFLICT: 'ITEM_VERSION_CONFLICT',
  ITEM_VERSION_REQUIRED: 'ITEM_VERSION_REQUIRED',
  PHOTO_NOT_FOUND: 'PHOTO_NOT_FOUND',
  PHOTO_PROCESSING_ERROR: 'PHOTO_PROCESSING_ERROR',
  PHOTO_REQUIRED: 'PHOTO_REQUIRED',
  PHOTO_TOO_LARGE: 'PHOTO_TOO_LARGE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
